# Gin HTTP server configuration.
server:
  address: ":6872"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# Application logger configuration.
logger:
  level: "all"
  stdout: true

ds_think_chat_model:
  api_key: ""
  base_url: ""
  model: ""

ds_quick_chat_model:
  api_key: ""
  base_url: ""
  model: ""

doubao_embedding_model:
  api_key: ""
  model: "text-embedding-v4"

agent_service_port: 6872
api_gateway_base_url: "http://127.0.0.1:8080"
milvus_addr: "127.0.0.1:19530"
docs_dir: "./docs"
