// Manager对外查询的 RPC 契约，不仅查询请求和响应，还包括数据记录字段分组

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v6.31.1
// source: query_api.proto

package queryapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	QueryService_QueryPerformance_FullMethodName   = "/monitor.proto.QueryService/QueryPerformance"
	QueryService_QueryTrend_FullMethodName         = "/monitor.proto.QueryService/QueryTrend"
	QueryService_QueryAnomaly_FullMethodName       = "/monitor.proto.QueryService/QueryAnomaly"
	QueryService_QueryScoreRank_FullMethodName     = "/monitor.proto.QueryService/QueryScoreRank"
	QueryService_QueryLatestScore_FullMethodName   = "/monitor.proto.QueryService/QueryLatestScore"
	QueryService_QueryNetDetail_FullMethodName     = "/monitor.proto.QueryService/QueryNetDetail"
	QueryService_QueryDiskDetail_FullMethodName    = "/monitor.proto.QueryService/QueryDiskDetail"
	QueryService_QueryMemDetail_FullMethodName     = "/monitor.proto.QueryService/QueryMemDetail"
	QueryService_QuerySoftIrqDetail_FullMethodName = "/monitor.proto.QueryService/QuerySoftIrqDetail"
)

// QueryServiceClient is the client API for QueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryServiceClient interface {
	// 时间段性能数据查询
	QueryPerformance(ctx context.Context, in *QueryPerformanceRequest, opts ...grpc.CallOption) (*QueryPerformanceResponse, error)
	// 变化率趋势查询
	QueryTrend(ctx context.Context, in *QueryTrendRequest, opts ...grpc.CallOption) (*QueryTrendResponse, error)
	// 异常数据查询
	QueryAnomaly(ctx context.Context, in *QueryAnomalyRequest, opts ...grpc.CallOption) (*QueryAnomalyResponse, error)
	// 评分排序查询
	QueryScoreRank(ctx context.Context, in *QueryScoreRankRequest, opts ...grpc.CallOption) (*QueryScoreRankResponse, error)
	// 最新评分查询
	QueryLatestScore(ctx context.Context, in *QueryLatestScoreRequest, opts ...grpc.CallOption) (*QueryLatestScoreResponse, error)
	// 详细数据查询
	QueryNetDetail(ctx context.Context, in *QueryDetailRequest, opts ...grpc.CallOption) (*QueryNetDetailResponse, error)
	QueryDiskDetail(ctx context.Context, in *QueryDetailRequest, opts ...grpc.CallOption) (*QueryDiskDetailResponse, error)
	QueryMemDetail(ctx context.Context, in *QueryDetailRequest, opts ...grpc.CallOption) (*QueryMemDetailResponse, error)
	QuerySoftIrqDetail(ctx context.Context, in *QueryDetailRequest, opts ...grpc.CallOption) (*QuerySoftIrqDetailResponse, error)
}

type queryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryServiceClient(cc grpc.ClientConnInterface) QueryServiceClient {
	return &queryServiceClient{cc}
}

func (c *queryServiceClient) QueryPerformance(ctx context.Context, in *QueryPerformanceRequest, opts ...grpc.CallOption) (*QueryPerformanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPerformanceResponse)
	err := c.cc.Invoke(ctx, QueryService_QueryPerformance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) QueryTrend(ctx context.Context, in *QueryTrendRequest, opts ...grpc.CallOption) (*QueryTrendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTrendResponse)
	err := c.cc.Invoke(ctx, QueryService_QueryTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) QueryAnomaly(ctx context.Context, in *QueryAnomalyRequest, opts ...grpc.CallOption) (*QueryAnomalyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryAnomalyResponse)
	err := c.cc.Invoke(ctx, QueryService_QueryAnomaly_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) QueryScoreRank(ctx context.Context, in *QueryScoreRankRequest, opts ...grpc.CallOption) (*QueryScoreRankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryScoreRankResponse)
	err := c.cc.Invoke(ctx, QueryService_QueryScoreRank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) QueryLatestScore(ctx context.Context, in *QueryLatestScoreRequest, opts ...grpc.CallOption) (*QueryLatestScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryLatestScoreResponse)
	err := c.cc.Invoke(ctx, QueryService_QueryLatestScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) QueryNetDetail(ctx context.Context, in *QueryDetailRequest, opts ...grpc.CallOption) (*QueryNetDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryNetDetailResponse)
	err := c.cc.Invoke(ctx, QueryService_QueryNetDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) QueryDiskDetail(ctx context.Context, in *QueryDetailRequest, opts ...grpc.CallOption) (*QueryDiskDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDiskDetailResponse)
	err := c.cc.Invoke(ctx, QueryService_QueryDiskDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) QueryMemDetail(ctx context.Context, in *QueryDetailRequest, opts ...grpc.CallOption) (*QueryMemDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryMemDetailResponse)
	err := c.cc.Invoke(ctx, QueryService_QueryMemDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) QuerySoftIrqDetail(ctx context.Context, in *QueryDetailRequest, opts ...grpc.CallOption) (*QuerySoftIrqDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySoftIrqDetailResponse)
	err := c.cc.Invoke(ctx, QueryService_QuerySoftIrqDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServiceServer is the server API for QueryService service.
// All implementations must embed UnimplementedQueryServiceServer
// for forward compatibility
type QueryServiceServer interface {
	// 时间段性能数据查询
	QueryPerformance(context.Context, *QueryPerformanceRequest) (*QueryPerformanceResponse, error)
	// 变化率趋势查询
	QueryTrend(context.Context, *QueryTrendRequest) (*QueryTrendResponse, error)
	// 异常数据查询
	QueryAnomaly(context.Context, *QueryAnomalyRequest) (*QueryAnomalyResponse, error)
	// 评分排序查询
	QueryScoreRank(context.Context, *QueryScoreRankRequest) (*QueryScoreRankResponse, error)
	// 最新评分查询
	QueryLatestScore(context.Context, *QueryLatestScoreRequest) (*QueryLatestScoreResponse, error)
	// 详细数据查询
	QueryNetDetail(context.Context, *QueryDetailRequest) (*QueryNetDetailResponse, error)
	QueryDiskDetail(context.Context, *QueryDetailRequest) (*QueryDiskDetailResponse, error)
	QueryMemDetail(context.Context, *QueryDetailRequest) (*QueryMemDetailResponse, error)
	QuerySoftIrqDetail(context.Context, *QueryDetailRequest) (*QuerySoftIrqDetailResponse, error)
	mustEmbedUnimplementedQueryServiceServer()
}

// UnimplementedQueryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServiceServer struct {
}

func (UnimplementedQueryServiceServer) QueryPerformance(context.Context, *QueryPerformanceRequest) (*QueryPerformanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryPerformance not implemented")
}
func (UnimplementedQueryServiceServer) QueryTrend(context.Context, *QueryTrendRequest) (*QueryTrendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTrend not implemented")
}
func (UnimplementedQueryServiceServer) QueryAnomaly(context.Context, *QueryAnomalyRequest) (*QueryAnomalyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryAnomaly not implemented")
}
func (UnimplementedQueryServiceServer) QueryScoreRank(context.Context, *QueryScoreRankRequest) (*QueryScoreRankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryScoreRank not implemented")
}
func (UnimplementedQueryServiceServer) QueryLatestScore(context.Context, *QueryLatestScoreRequest) (*QueryLatestScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLatestScore not implemented")
}
func (UnimplementedQueryServiceServer) QueryNetDetail(context.Context, *QueryDetailRequest) (*QueryNetDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryNetDetail not implemented")
}
func (UnimplementedQueryServiceServer) QueryDiskDetail(context.Context, *QueryDetailRequest) (*QueryDiskDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDiskDetail not implemented")
}
func (UnimplementedQueryServiceServer) QueryMemDetail(context.Context, *QueryDetailRequest) (*QueryMemDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryMemDetail not implemented")
}
func (UnimplementedQueryServiceServer) QuerySoftIrqDetail(context.Context, *QueryDetailRequest) (*QuerySoftIrqDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuerySoftIrqDetail not implemented")
}
func (UnimplementedQueryServiceServer) mustEmbedUnimplementedQueryServiceServer() {}

// UnsafeQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServiceServer will
// result in compilation errors.
type UnsafeQueryServiceServer interface {
	mustEmbedUnimplementedQueryServiceServer()
}

func RegisterQueryServiceServer(s grpc.ServiceRegistrar, srv QueryServiceServer) {
	s.RegisterService(&QueryService_ServiceDesc, srv)
}

func _QueryService_QueryPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).QueryPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_QueryPerformance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).QueryPerformance(ctx, req.(*QueryPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_QueryTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).QueryTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_QueryTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).QueryTrend(ctx, req.(*QueryTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_QueryAnomaly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAnomalyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).QueryAnomaly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_QueryAnomaly_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).QueryAnomaly(ctx, req.(*QueryAnomalyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_QueryScoreRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryScoreRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).QueryScoreRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_QueryScoreRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).QueryScoreRank(ctx, req.(*QueryScoreRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_QueryLatestScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLatestScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).QueryLatestScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_QueryLatestScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).QueryLatestScore(ctx, req.(*QueryLatestScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_QueryNetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).QueryNetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_QueryNetDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).QueryNetDetail(ctx, req.(*QueryDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_QueryDiskDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).QueryDiskDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_QueryDiskDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).QueryDiskDetail(ctx, req.(*QueryDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_QueryMemDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).QueryMemDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_QueryMemDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).QueryMemDetail(ctx, req.(*QueryDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_QuerySoftIrqDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).QuerySoftIrqDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_QuerySoftIrqDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).QuerySoftIrqDetail(ctx, req.(*QueryDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueryService_ServiceDesc is the grpc.ServiceDesc for QueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.proto.QueryService",
	HandlerType: (*QueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryPerformance",
			Handler:    _QueryService_QueryPerformance_Handler,
		},
		{
			MethodName: "QueryTrend",
			Handler:    _QueryService_QueryTrend_Handler,
		},
		{
			MethodName: "QueryAnomaly",
			Handler:    _QueryService_QueryAnomaly_Handler,
		},
		{
			MethodName: "QueryScoreRank",
			Handler:    _QueryService_QueryScoreRank_Handler,
		},
		{
			MethodName: "QueryLatestScore",
			Handler:    _QueryService_QueryLatestScore_Handler,
		},
		{
			MethodName: "QueryNetDetail",
			Handler:    _QueryService_QueryNetDetail_Handler,
		},
		{
			MethodName: "QueryDiskDetail",
			Handler:    _QueryService_QueryDiskDetail_Handler,
		},
		{
			MethodName: "QueryMemDetail",
			Handler:    _QueryService_QueryMemDetail_Handler,
		},
		{
			MethodName: "QuerySoftIrqDetail",
			Handler:    _QueryService_QuerySoftIrqDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "query_api.proto",
}
